version: '2'
services:
  zookeeper:
    image: mesoscloud/zookeeper:3.4.8-centos-7
    restart: always
    network_mode: "host"
    volumes:
    - "./data/zookeeper:/tmp/zookeeper"
    environment:
      MYID: 1
  mesos-master:
    image: mesosphere/mesos-master:1.5.0
    restart: always
    network_mode: "host"
    volumes:
    - "/etc/hosts:/etc/hosts:ro"
    - "./data/mesos-master/log:/var/log/mesos"
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: zk://${HOSTNAME}:2181/mesos
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    depends_on:
    - zookeeper
  mesos-slave:
    image: mesosphere/mesos-slave:1.5.0
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://${HOSTNAME}:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker
      MESOS_ISOLATOR: cgroups/cpu,cgroups/mem
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    volumes:
    - "/etc/hosts:/etc/hosts:ro"
    - "./data/mesos-slave/tmp:/var/tmp/mesos"
    - "./data/mesos-slave/log:/var/log/mesos"
    - "/cgroup:/cgroup"
    - "/sys:/sys"
    - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
    - mesos-master
  marathon:
    image: mesosphere/marathon:v1.5.7
    restart: always
    network_mode: "host"
    volumes:
    - "/etc/hosts:/etc/hosts:ro"
    command: "--master=zk://${HOSTNAME}:2181/mesos --zk=zk://${HOSTNAME}:2181/marathon"
    depends_on:
    - mesos-master
